server:
  port: ${SERVER_PORT:80}
  jetty:
    threads:
      min: ${HTTP_MIN_THREADS:8}
      max: ${HTTP_MAX_THREADS:100}
      max-queue-capacity: ${HTTP_MAX_QUEUE:100}

logging:
  config: "classpath:logback-spring.xml"

spring:
  application:
    name: spring-data-rest-demo
  main:
    allow-bean-definition-overriding: true
  data:
    rest:
      base-path: /api/data/
      default-page-size: 100
  jpa:
    database: postgresql
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}?currentSchema=social
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      # small and fixed size DB pool is much preferred (see https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing)
      minimum-idle: ${DB_HIKARI_MIN_IDLE:4}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:4}
      auto-commit: ${DB_HIKARI_AUTO_COMMIT:false}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:30000}
      pool-name: db-hikari-pool
      validation-timeout: ${DB_VALIDATION_TIMEOUT:10000}
  transaction:
    default-timeout: ${DEFAULT_TRANSACTION_TIMEOUT:10}
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    validate-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:/db/migration
    schemas: social
    baseline-on-migrate: true
  jackson:
    serialization:
      WRITE_DATE_KEYS_AS_TIMESTAMPS: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  server:
    # Extract actuator to another jetty server for performance reason
    port: ${MANAGEMENT_SERVER_PORT:88}
